/**
 * AIDIS Real-Time Event Types
 * Shared event model for Server-Sent Events (SSE) implementation
 * 
 * These types define the structure of events broadcast when database
 * records change. Events are generated by PostgreSQL triggers and
 * distributed to connected clients via SSE.
 */

/**
 * Database entities that support real-time updates
 */
export type AidisEntity = 
  | 'contexts'      // Development contexts
  | 'tasks'         // Task management
  | 'decisions'     // Technical decisions (technical_decisions table)
  | 'projects'      // Project definitions
  | 'sessions';     // Session tracking

/**
 * Database operations that trigger events
 */
export type AidisAction = 
  | 'insert'        // New record created
  | 'update'        // Existing record updated
  | 'delete';       // Record deleted

/**
 * Database event payload
 * 
 * This is the core event structure broadcast via SSE when database
 * records change. The payload is intentionally minimal to reduce
 * bandwidth and coupling. Clients should refetch full record details
 * using the provided ID.
 * 
 * @template T - Optional data payload for small updates (use sparingly)
 */
export interface AidisDbEvent<T = unknown> {
  /**
   * Entity type that changed
   */
  entity: AidisEntity;
  
  /**
   * Database operation performed
   */
  action: AidisAction;
  
  /**
   * Record ID (UUID)
   */
  id: string;
  
  /**
   * Project ID for filtering (if applicable)
   * Used to filter events by project context
   */
  projectId?: string;
  
  /**
   * Timestamp when the event occurred (ISO 8601 format)
   * Generated by PostgreSQL trigger
   */
  at: string;
  
  /**
   * Optional minimal data payload
   * 
   * Keep this small (<1KB recommended). For most use cases,
   * clients should refetch the full record using the ID.
   * This field is useful for:
   * - Status changes
   * - Title updates
   * - Other small, frequently-accessed fields
   */
  data?: T;
}

/**
 * SSE connection options
 */
export interface SseSubscriptionOptions {
  /**
   * Filter events by entity types
   * If omitted, all entity types are included
   */
  entities?: AidisEntity[];
  
  /**
   * Filter events by project ID
   * If omitted, events from all projects are included
   */
  projectId?: string;
}

/**
 * SSE system message (non-database event)
 */
export interface SseSystemMessage {
  type: 'system';
  message: string;
  timestamp: string;
  [key: string]: unknown;
}

/**
 * Union type for all SSE message types
 */
export type SseMessage = AidisDbEvent | SseSystemMessage;
