-- Migration 023: Add Session Token Tracking
-- TS006-2: Token Counting Implementation
-- Created: 2025-09-30
-- Purpose: Add detailed token tracking columns to sessions table

BEGIN;

-- Add token tracking columns
ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS input_tokens BIGINT DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS output_tokens BIGINT DEFAULT 0 NOT NULL,
  ADD COLUMN IF NOT EXISTS total_tokens BIGINT DEFAULT 0 NOT NULL;

-- Migrate existing tokens_used data to total_tokens
UPDATE sessions
SET total_tokens = COALESCE(tokens_used, 0)
WHERE total_tokens = 0 AND tokens_used > 0;

-- Add indexes for performance on token queries
CREATE INDEX IF NOT EXISTS idx_sessions_total_tokens ON sessions(total_tokens);
CREATE INDEX IF NOT EXISTS idx_sessions_input_tokens ON sessions(input_tokens);

-- Add comments for documentation
COMMENT ON COLUMN sessions.input_tokens IS 'Estimated input tokens consumed by this session (characters/4)';
COMMENT ON COLUMN sessions.output_tokens IS 'Estimated output tokens generated by this session (characters/4)';
COMMENT ON COLUMN sessions.total_tokens IS 'Total tokens (input + output) for this session';

-- Verify the migration
DO $$
DECLARE
  col_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO col_count
  FROM information_schema.columns
  WHERE table_name = 'sessions'
    AND column_name IN ('input_tokens', 'output_tokens', 'total_tokens');

  IF col_count = 3 THEN
    RAISE NOTICE 'Migration 023 completed successfully: All token tracking columns added';
  ELSE
    RAISE EXCEPTION 'Migration 023 failed: Expected 3 columns, found %', col_count;
  END IF;
END $$;

COMMIT;
